/* export enum BankCode {
  BANCO_CENTRAL_DE_BOLIVIA = '1004',
  BANCO_DE_CREDITO = '1005',
  BANCO_UNION = '1014',
}
 */

export enum BankCode {
  BANCO_DE_CREDITO = '1005',
  BANCO_ECONOMICO_SA = '1016',
  BANCO_FORTALEZA = '1034',
  BANCO_GANADERO_SA = '1018',
  BANCO_FIE = '1033',
  BANCO_BISA_SA = '1009',
  BANCO_MERCANTIL_SANTA_CRUZ = '1003',
  BANCO_DE_LA_NACION_ARGENTINA = '1007',
  BANCO_NACIONAL_DE_BOLIVIA_SA = '1001',
  BANCO_SOLIDARIO_SA = '1017',
  BANCO_UNION_SA = '1014',

  COOPERATIVA_DE_AHORRO_Y_CREDITO_ABIERTA_COMARAPA = 'MLD3022',
  COOPERATIVA_DE_AHORRO_Y_CREDITO_ABIERTA_CATEDRAL = 'MLD3030',
  EL_CHOROLQUE_RL = 'MLD3026',
  COOPERATIVA_FACTIMA = '3003',
  COOPERATIVA_DE_AHORRO_Y_CREDITO_ABIERTA_INCA_HUASI_LTDA = 'MLD3012',
  COOPERATIVA_JESUS_NAZARENO = '3001',
  COOPERATIVA_DE_AHORRO_Y_CREDITO_ABIERTA_MAGISTERI = 'MLD3048',
  COOPERATIVA_DE_AHORRO_Y_CREDITO_MADRE_Y_MAESTRA_LT = 'MLD3028',
  COOPERATIVA_DE_AHORRO_Y_CREDITO_ABIERTA = 'MLD3034',
  COOPERATIVA_DE_AHORRO_Y_CREDITO_ABIERTA_PIO_X_LTDA = 'MLD3011',
  COOPERATIVA_DE_AHORRO_Y_CREDITO_ABIERTA_QUILLACOLLO_LTDA = '3015',
  COOPERATIVA_SAN_MARTIN_DE_PORRES = '3002',
  COOPERATIVA_SAN_MATEO = '3025',
  COOPERATIVA_DE_AHORRO_Y_CREDITO_TRINIDAD_LTDA = 'MLD3021',

  CIDRE_IFD = '27002',
  CRECER_IFD = '27003',
  DIACONIA_IFD = '27004',
  INSTITUCION_FINANCIERA_DE_DESARROLLO_IDEPRO = '27009',
  INSTITUCION_FINANCIERA_DE_DESARROLLO_PRO_MUJER = '27012',

  BANCO_ECONOMICO_SA_MLD = 'MLD1016',
  BANCO_FORTALEZA_MLD = 'MLD1034',
  BANCO_GANADERO_SA_MLD = 'MLD1018',
  BANCO_FIE_MLD = 'MLD1033',
  BANCO_NACIONAL_DE_BOLIVIA_SA_MLD = 'MLD1001',
  BANCO_SOLIDARIO_SA_MLD = 'MLD1017',
  BANCO_UNION_SA_MLD = 'MLD1014',

  TIGO_MONEY = '53001',

  BANCO_PYME_DE_LA_COMUNIDAD = '74003',
  BANCO_PYME_ECOFUTURO_SA = '74002',

  COOPERATIVA_SAN_MATEO_UNI = 'UNI3025',
  INSTITUCION_FINANCIERA_DE_DESARROLLO_IDEPRO_UNI = 'UNI27009',
  INSTITUCION_FINANCIERA_DE_DESARROLLO_PRO_MUJER_UNI = 'UNI27012',

  LA_PRIMERA_ENTIDAD_FINANCIERA_DE_VIVIENDA = 'MLD75001',
  LA_PROMOTORA_EFV = '75003',
}
