export enum ValidPermissions {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  READ_DASBOARD_ADMIN = 'READ_DASBOARD_ADMIN',
  READ_DASBOARD_COMPANY = 'READ_DASBOARD_COMPANY',

  CLOSE = 'CLOSE',
  CONFIRM = 'CONFIRM',
  CANCEL = 'CANCEL',

  READ_CASHIERS = 'READ_CASHIERS',
  UPDATE_CASHIERS = 'UPDATE_CASHIERS',

  READ_OWNER = 'READ_OWNER',

  RECHARGE = 'RECHARGE',
}
