export enum ValidPermissions {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  CREATE_ADMIN = 'CREATE_ADMIN',
  READ_ADMIN = 'READ_ADMIN',
  READ_COMPANY = 'READ_COMPANY',

  PAY = 'PAY',

  CLOSE = 'CLOSE',
  CONFIRM = 'CONFIRM',
  CANCEL = 'CANCEL',

  READ_CASHIERS = 'READ_CASHIERS',
  UPDATE_CASHIERS = 'UPDATE_CASHIERS',

  READ_OWNER = 'READ_OWNER',

  RECHARGE = 'RECHARGE',
}
